---
- name: "Delete Elasticache Instance"
  elasticache:
    name:                    "{{ [default_account_alias, default_platform , item.name] | join('-') }}"
    state:                   absent
    region:                  "{{ default_region }}"
    wait: yes
  loop: "{{ elasticache_metadata.instances }}"

- name: "Delete Elasticache Subnet Group"
  elasticache_subnet_group:
    state: absent
    name: "{{ default_prefix | lower }}{{ REGIONS[default_region] | lower }}-{{ default_account_alias | lower }}-{{default_platform | lower}}-{{item.value.name|lower}}"
    region: "{{ default_region }}"
  with_dict: "{{ elasticache_metadata.subnet_group}}"
  register: create_elasticache_subnet_group
