---
- name: "Create Virtual Private Cloud Subnet"
  ec2_vpc_subnet:
    vpc_id: "{{vpc.id}}"
    cidr: "{{item.value.cidr}}"
    az: "{{ default_region }}{{ item.value.az_alias}}"
    region: "{{default_region}}"
    state: absent
  with_dict: "{{ vpc_subnets_metadata }}"
