---
- hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - group_vars/default.yml
    - group_vars/metadata.yml
  vars:
    is_absent: true
  roles:
    - 12_Autoscaling
    - 11_ALB
    - 10_TargetGroup
    - 9_EC2
    - 8_IAM
    - 7_SecurityGroup
    - 6_NACL
    - 5_RoutingTable