---
- hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - group_vars/default.yml
    - group_vars/metadata.yml
  roles:
    - 1_Vpc
    - 2_Subnet
    - 3_InternetGateway
    - 4_NatGateway
    - 5_RoutingTable
    - 6_NACL
    - 7_SecurityGroup
    - 8_IAM
    - 9_EC2
    - 10_TargetGroup
    - 11_ALB
    - 12_Autoscaling
    - 13_RDS
    - 14_S3


