---
- hosts: localhost
  gather_facts: no
  vars:
    vhosts:
      git_branch_1:
        - { a: example.com, customer: a }
        - { a: example.com, customer: b }
        - { a: example.org, customer: a }
      git_branch_2:
        - { a: example.com, customer: x }
        - { a: example.org, customer: y }
  tasks:
    - name: add new key / value pairs to dict
      set_fact:
        my_dict_var: "{{ my_dict_var | combine({item.key: item.value}) }}"
      with_items:
        - { key: 'key01', value: 'value 01' }
        - { key: 'key02', value: 'value 03' }
        - { key: 'key03', value: 'value 04' }