- name: Get details on specific nat gateways
  ec2_vpc_nat_gateway_info:
    filters:
      state: ['available']
    region: "{{default_region}}"
  register: specific_ngws

- name: "Delete Nat Gateway"
  ec2_vpc_nat_gateway:
    nat_gateway_id: "{{ item.nat_gateway_id }}"
    region: "{{default_region}}"
    wait: yes
    release_eip: yes
    state: absent
  loop: "{{specific_ngws.result}}"
