---
- name: "Create Public RoutingTable Rule And Assign Public Subnets"
  ec2_vpc_route_table:
    vpc_id: "{{vpc.id}}"
    region: "{{default_region}}"
    tags:
      Name: "{{default_prefix}}{{REGIONS[default_region]}}-{{default_account_alias}}-{{default_platform}}-{{ vpc_routing_tables.public.number }}"
      Company: "{{default_prefix}}"
      Country: KR
      Service: Public RouteTable
      Stage: "{{default_stage}}"
    subnets: "{{ vpc_routing_tables.public.subnets }}"
    routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ igw.gateway_id }}"


- name: "Create Private RoutingTable Rule With Nat Gateway And Assign Public Subnets"
  when: item.value.nat is defined
  ec2_vpc_route_table:
    vpc_id: "{{vpc.id}}"
    region: "{{default_region}}"
    tags:
      Name: "{{default_prefix}}{{REGIONS[default_region]}}-{{default_account_alias}}-{{default_platform}}-{{ item.value.domain}}-{{ item.value.number}}"
      Company: "{{default_prefix}}"
      Country: KR
      Service: "{{item.value.service}}"
      Stage: "{{default_stage}}"
    subnets: "{{ item.value.subnets }}"
    routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ nat_gateway[item.value.nat].nat_gateway_id }}"
  with_dict: "{{ vpc_routing_tables.private }}"


- name: "Create Private RoutingTable Rule Without Nat Gateway And Assign Public Subnets"
  when: item.value.nat is undefined
  ec2_vpc_route_table:
    vpc_id: "{{vpc.id}}"
    region: "{{default_region}}"
    tags:
      Name: "{{default_prefix}}{{REGIONS[default_region]}}-{{default_account_alias}}-{{default_platform}}-{{ item.value.domain}}-{{ item.value.number}}"
      Company: "{{default_prefix}}"
      Country: KR
      Service: "{{item.value.service}}"
      Stage: "{{default_stage}}"
    subnets: "{{ item.value.subnets }}"
  with_dict: "{{ vpc_routing_tables.private }}"
