---
- name: "Get Virtual Private Cloud Information"
  when: vpc is undefined
  ec2_vpc_net_info:
    region: "{{default_region}}"
    filters:
      "tag:Name": "{{ default_prefix }}{{ REGIONS[default_region] }}-{{ default_account_alias }}"
  register: get_vpc

- name: "Gathering Virtual Private Cloud Information"
  ansible.builtin.set_fact:
    vpc: '{{ get_vpc.vpcs | first }}'
#    vpc: '{{ get_vpc | first }}'

- name: "Delete Security Group Rule"
  ec2_group:
    name: "{{default_prefix}}{{REGIONS[default_region]}}-{{default_account_alias}}-{{default_platform}}-{{item.name}}"
    description: "{{item.description}}"
    region: "{{default_region}}"
    tags:
      Name: "{{default_prefix}}{{REGIONS[default_region]}}-{{default_account_alias}}-{{default_platform}}-{{item.name}}"
    vpc_id: "{{vpc.id}}"
    purge_rules: true
    purge_rules_egress: true
    rules:
      - proto: tcp
        from_port: 443
        to_port: 443
        cidr_ip: 0.0.0.0/0
    rules_egress:
      - proto: tcp
        from_port: 3306
        to_port: 3306
        cidr_ip: 0.0.0.0/0
  loop: "{{ ec2_security_groups_metadata }}"

- name: Sleep for 15 seconds and continue with play
  wait_for:
    timeout: 20

- name: "Delete Security Group"
  ec2_group:
    name: "{{default_prefix}}{{REGIONS[default_region]}}-{{default_account_alias}}-{{default_platform}}-{{item.name}}"
    description: "{{item.description}}"
    region: "{{default_region}}"
    state: absent
  loop: "{{ ec2_security_groups_metadata }}"
