---
- name: "Delete Security Group Rule"
  ec2_group:
    name: "{{default_prefix}}{{REGIONS[default_region]}}-{{default_account_alias}}-{{default_platform}}-{{item.name}}"
    description: "{{item.description}}"
    region: "{{default_region}}"
    vpc_id: ""
    tags:
      Name: "{{default_prefix}}{{REGIONS[default_region]}}-{{default_account_alias}}-{{default_platform}}-{{item.name}}"
  loop: "{{ ec2_security_groups_metadata }}"

- name: "Delete Security Group"
  ec2_group:
    name: "{{default_prefix}}{{REGIONS[default_region]}}-{{default_account_alias}}-{{default_platform}}-{{item.name}}"
    description: "{{item.description}}"
    region: "{{default_region}}"
    state: absent
  loop: "{{ ec2_security_groups_metadata }}"
