---
- name: "Create EC2 Bastion Instance"
  ec2:
    key_name: "{{ ec2_bastion.key_name }}"
    image: "{{ ec2_bastion.image }}"
    instance_type: t2.micro
    region: "{{ default_region }}"
    vpc_subnet_id: "{{subnets[ec2_bastion.subnet].id}}"
    assign_public_ip: yes
    instance_tags:
      Name: "{{ default_prefix }}{{ REGIONS[default_region] }}-{{ default_account_alias }}-a-{{default_platform}}-bastion"
    group: "{{ec2_bastion.security_groups}}"
    wait: true
    count: 1
