- name: "Create IAM Role For EC2 Instance Profile"
  iam_role:
    name: "{{item.name}}"
    region: "{{ default_region }}"
    assume_role_policy_document: "{{ lookup( 'file', 'template/ec2_role.json') }}"
    managed_policy: "{{item.managed_polices | default([])}}"
  loop: "{{aws_iam_role}}"

- name: "Create IAM Policy"
  when: item.policy_file_name is defined
  iam_policy:
    iam_name: "{{item.iam_name}}"
    policy_name: "{{item.policy_name}}"
    iam_type: "{{item.iam_type}}"
    region: "{{ default_region }}"
    policy_json: "{{ lookup( 'file', ['template', item.policy_file_name]|join('/' )) }}"
    state: present
  loop: "{{aws_iam_policy}}"
