- name: "Create and associate production DMZ network ACL with DMZ subnets"
  ec2_vpc_nacl:
    vpc_id: "{{vpc.id}}"
    name: "{{default_prefix}}{{REGIONS[default_region]}}-{{default_account_alias}}-nacl-01"
    region: "{{default_region}}"
    subnets: "{{ subnets |  dict2items | map(attribute='value') | map(attribute='id') | list }}"
    ingress:
      - [100, 'all', 'allow', '0.0.0.0/0', null, null, null, null]
    egress:
      - [100, 'all', 'allow', '0.0.0.0/0', null, null, null, null]
    state: 'present'