---
- name: "Delete Target Group"
  elb_target_group:
    name: "{{ default_account_alias }}-{{default_platform}}-{{alb[item.alb].system}}-ALB-{{alb[item.alb].name}}-{{ item.name }}"
    state: absent
    region: "{{default_region}}"
    protocol: "{{ item.protocol }}"
    port: "{{ item.port }}"
    vpc_id: ""
  loop: "{{ target_group }}"
