- name: Install main configuration file
  template:
    src: httpd.conf.j2
    dest: /usr/local/apache/conf/httpd.conf
    owner: root
    group: root
    setype: httpd_config_t
    mode: '0644'
  notify: restart httpd
  tags: httpd

- name: restart httpd
  service:
    name: httpd
    state: restarted